### ISSUE TITLE
Vacancies and Research Threads not filled

### ISSUE THREAD

**Issue by TheProjectsGuy** [RoboticsIIITH/roboticsiiith.github.io#10]
Page: https://robotics.iiit.ac.in/vacancies/
Probable file: https://github.com/RoboticsIIITH/roboticsiiith.github.io/blob/main/_pages/openings.md

The file has to be populated with our current data. It mentions `Leiden University` (at least that can be changed).

Should openings be under professors (in `_pages/faculty-pages`) or global (in `_pages/openings.md`)? I think linking the global openings to faculty-specific pages will be better.
Also, research threads under different faculties are not filled. Maybe we can have the faculty-specific students handle this.

**Comment by TheProjectsGuy** [comment]
Maybe this can be a part of #5

**Comment by TheProjectsGuy** [comment]
We also need to change the favicon
![image](https://user-images.githubusercontent.com/29420733/178980373-5b5d0d32-9ba6-4bed-8566-1d67dfa753f2.png)

The original favicon belongs to [Allan Lab @ Leiden University](https://www.allanlab.org/)

**Comment by mohdomama** [comment]
Done with the favicon issue.

**Comment by mohdomama** [comment]
Done with research thread

**Comment by mohdomama** [comment]
All page update issues are being tracked at #15
